FROM python:3.12-slim

WORKDIR /app

COPY back/projeto-gestao-tccs/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY back/projeto-gestao-tccs/ .

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"]
